### ISSUE TITLE
Arguments to side_effect

### ISSUE THREAD

**Issue by jberger** [stevieb9/mock-sub#5]
As currently constituted, the `side_effect` has no access to the called_with arguments (short of closing over the mock object in the side effect). Perhaps consider passing in the arguments to the mock? 

reference: https://docs.python.org/3/library/unittest.mock.html#quick-guide

**Comment by stevieb9** [comment]
Hi Joel, this should now be fixed in  5a76365. Could you have a look and/or test to see that I understood what you were hoping for here, then I'll close?

Thanks!

**Comment by jberger** [comment]
looks good! btw if you had used "closes #5" in your commit message then it would have automagically close this issue. :)

**Comment by stevieb9** [comment]
Ohhh I didn't know that!

Note I wrote this module specifically because I just started using
MagicMock in Python (I code in Python at my job), and wanted the same in
Perl.

Please feel free to create PRs for anything here, or provide insight into
any implementation details; I'm still not overly familiar with Python's
mock() yet :) All help is greatly appreciated.

Cheers,

Steve
